[package]
name = "bcc"
version = "0.0.3"
authors = ["Julia Evans <julia@jvns.ca>"]
description = "Idiomatic Rust bindings for BPF Compiler Collection (BCC)"
keywords = ["bpf", "bindings", "bcc"]
license = "MIT"
repository = "https://github.com/jvns/rust-bcc"
readme = "README.md"
documentation = "https://docs.rs/bcc/0.0.2/bcc/"
homepage = "https://github.com/jvns/rust-bcc"

[dependencies]
libc = "0.2.36"
bcc-sys = "0.4.0"
failure = "0.1.1"
byteorder = "1"
num_cpus = "1.0"
